version: '3'

services:
  task_waiter:
    build: .
    volumes:
      - $HOME/.aws:/root/.aws
      - ./task_wait_and_fetch_data.py:/app/task_wait_and_fetch_data.py
    stdin_open: true 
    tty: true